name: Tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
        options: >-
          --health-cmd mongosh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install backend dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install test dependencies
      run: |
        pip install -r tests/requirements.txt
    
    - name: Run tests
      env:
        MONGODB_URL: mongodb://admin:password@localhost:27017/pokemon_binder_test?authSource=admin
        JWT_SECRET_KEY: test_secret_key_for_ci
      run: |
        export PYTHONPATH="${PYTHONPATH}:${PWD}/backend"
        pytest tests/ -v
